language: node_js
node_js:
  - "10.17"
  - "12.13"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - npm test:check-coverage
after_script:
  - npm run report-coverage
