---
- name: api deploy
  hosts: west
  remote_user: hank
  vars:
    workdir: /home/hank/code/src/github.com/aliencyborg/big-time-api
  tasks:
    - name: ensure code/src/github.com/aliencyborg directory is present
      file:
        path: /home/hank/code/src/github.com/aliencyborg
        state: directory
      tags: [ prod, stage ]

    ## STAGE ##

    - name: clone or update big-time-api repository (stage)
      git:
        accept_hostkey: yes
        dest: "{{ workdir }}"
        key_file: /home/hank/.ssh/id_rsa
        repo: 'git@github.com:aliencyborg/big-time-api.git'
        update: yes
        version: stage
      retries: 2
      tags: stage

    - name: ensure mongo data container (stage)
      docker_container:
        image: mongo:3.4
        name: big-time-stage-db-data
        state: stopped
      tags: stage

    - name: run mongo db container (stage)
      docker_container:
        image: mongo:3.4
        name: big-time-stage-db
        state: started
        volumes_from:
          - big-time-stage-db-data
      tags: stage

    - name: build docker image (stage)
      docker_image:
        force_source: yes
        name: big-time-api
        source: build
        tag: stage
        build:
          path: "{{ workdir }}"
          pull: no
      tags: stage

    - name: run api container (stage)
      docker_container:
        image: big-time-api:stage
        name: big-time-api-stage
        ports: '4040:4040'
        state: started
        env:
          NODE_ENV: production
          LETSENCRYPT_HOST: 'bigtime.aliencyb.org'
          MONGO_HOST: 'mongodb://mongo/big-time'
          MONGO_PORT: 27017
          PORT: 4040
          VIRTUAL_HOST: 'bigtime.aliencyb.org'
          VIRTUAL_PORT: 4040
        links:
          - 'big-time-stage-db:mongo'
      tags: stage

    ## PRODUCTION ##
